FROM python:3.9
ADD . /mat2-web
WORKDIR /mat2-web
RUN apt-get update \
&&  apt-get install --no-install-recommends --no-install-suggests --yes \
    python3-gi \
    python3-gi-cairo \
    gir1.2-poppler-0.18 \
    gir1.2-gdkpixbuf-2.0 \
    libimage-exiftool-perl \
    libgirepository1.0-dev \
    nodejs npm \
&&  pip install -r requirements.txt \
&&  npm i \
&&  npm install --global postcss postcss-cli \
&&  rm -rf /var/cache/apt/* /var/lib/apt/lists/*
CMD flask run --host=0.0.0.0

