version: '2'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.development
        environment:
            - FLASK_APP=main.py
            - FLASK_ENV=development
            - MAT2_ALLOW_ORIGIN_WHITELIST=*
        ports:
            - "5000:5000"
        volumes:
            - .:/mat2-web
        restart: always
